- name: "Get {{ item }}'s lingering state"
  command: loginctl --property Linger --value show-user {{ item }}
  changed_when: False
  check_mode: False
  failed_when: False
  register: result

# Spawn a user manager for this user at system start-up time. This allows
# enabled user units to start without that user being logged in.
- name: Enable lingering for {{ item }}
  command: loginctl enable-linger {{ item }}
  when: result.stdout != 'yes'
  become: true
  become_user: '{{ item }}'

- name: Get passwd information about {{ item }}
  getent:
    database: passwd
    key: '{{ item }}'
    split: ':'

# XDG_RUNTIME_DIR must be set, or else the systemd module will be unable to
# contact the user's DBus instance. In no particular order, see:
#
# * https://github.com/ansible/ansible/issues/27631
# * https://stackoverflow.com/questions/34167257/can-i-control-a-user-systemd-using-systemctl-user-after-sudo-su-myuser
# * https://uggedal.com/journal/ansible-systemd-user/
# * https://unix.stackexchange.com/questions/346841/why-does-sudo-i-not-set-xdg-runtime-dir-for-the-target-user
# * https://www.freedesktop.org/software/systemd/man/pam_systemd.html
- name: Start and enable syncthing for {{ item }}
  systemd:
    name: syncthing.service
    state: started
    enabled: true
    user: true
    daemon_reload: true
  environment:
    XDG_RUNTIME_DIR: /run/user/{{ getent_passwd[item][1] }}
  become: true
  become_user: "{{ item }}"
