- block:

  - name: Remove outdated custom executables
    file:
      path: "{{ user_ichimonji10_home }}/.local/bin/{{ item }}"
      state: absent
    with_items:
    - psmash-runner-3
    - psmash-runner-3-qpid
    - psmash-runner-3-rabbitmq

  - name: Install custom executables into ~/.local/bin
    copy:
      src: local_bin/
      dest: "{{ user_ichimonji10_home }}/.local/bin/"
      mode: 0755

  - name: Delete outdated psmash-ssh executable
    file:
      path: "{{ user_ichimonji10_home }}/.local/bin/psmash-ssh"
      state: absent

  - name: Create "{{ user_ichimonji10_home }}/.config/libvirt"
    file:
      state: directory
      path: "{{ user_ichimonji10_home }}/.config/libvirt"

  - name: Install libvirt configuration file
    copy:
      src: libvirt.conf
      dest: "{{ user_ichimonji10_home }}/.config/libvirt/libvirt.conf"

  become: true
  become_user: ichimonji10
