- block:

  - name: Install dnsmasq
    pacman:
      name: dnsmasq
      state: present

  # When dnsmasq receives a SIGHUP signal (as from `systemctl reload`), it does
  # *not* re-read its configuration file. See dnsmasq(8).
  - name: Install dnsmasq configuration file
    template:
      src: dnsmasq.conf
      dest: /etc/dnsmasq.conf
    notify: Restart dnsmasq
    when:
    - dnsmasq_lan_if is defined
    - dnsmasq_dmz_if is defined
    - dnsmasq_wlan_if is defined

  - name: Start and enable dnsmasq
    systemd:
      name: dnsmasq.service
      state: started
      enabled: yes
      daemon_reload: yes

  become: true
