- name: Set timezone
  timezone:
    # Time zones like US/Eastern (i.e. EST) are fixed. They don't respect
    # daylight savings time offsets.
    name: America/New_York

- name: Start and enable systemd-timesyncd
  systemd:
    name: systemd-timesyncd.service
    state: started
    enabled: yes
