# We don't create this group, because:
#
# * The system package manager probably expects this group to have certain
#   properties, like a certain ID.
# * It should be present in a base installation anyway.
- name: Give password-protected sudo privileges to the wheel group
  copy:
    src: wheel-group
    dest: /etc/sudoers.d/
    validate: 'visudo --check --file %s'
    mode: 0440
  become: true
