- hosts: all
  roles:
    - intel-ucode
    - lm-sensors
    - locale
    - msmtp
    - nftables
    - pkgfile
    - reflector
    - services
    - smartd
    - time
    - user-ichimonji10
  tasks:
    - name: Install tree
      pacman:
        name: tree

- hosts: all:!pine.ichimonji10.name
  roles:
    - crda

- hosts: workstations
  roles:
    - desktop-environment
    - picocom

- hosts: servers
  roles:
    - sshd
    - role: dynamic-dns
      when: dynamic_dns_urls is defined

- hosts: servers:beech.ichimonji10.name
  roles:
    - apcupsd

- hosts: servers:!routers
  roles:
    - netctl-generic

- hosts: routers
  roles:
    - dnsmasq
    # NOTE: Execute this play only over a wired connection.
    - role: hostapd
      when: hostapd_passphrase is defined
    - netctl-routers
    - wlan-secure

- hosts: vm-hosts
  roles:
    - libvirtd

- hosts: btrfs-hosts
  roles:
    - btrfs-balance
    - btrfs-scrub

# Why make an intersection between a group and a single host, instead of simply
# listing a single host? Well, what if this host is removed from the group?
- hosts: btrfs-hosts:&pine.ichimonji10.name
  roles:
    - btrfs-subvolume

- hosts: servers:&pine.ichimonji10.name
  roles:
    # NOTE: Make sure to install SSL certificates.
    - nginx
    - transmission
    - user-googoo
    - user-subsonic-backup

- hosts: '!amelanchier.ichimonji10.name'
  roles:
    - systemd-boot-pacman-hook

- hosts: pine.ichimonji10.name
  roles:
    - user-ichimonji10
    - role: borg-backup
      when:
        - borg_backup_passphrase is defined
        - borg_backup_user is defined
      vars:
        borg_backup_directories:
          - ~/books
          - ~/docs
          - ~/pictures
        borg_backup_user: ichimonji10

- hosts: pine.ichimonji10.name
  roles:
    - user-googoo
    - role: borg-backup
      when:
        - borg_backup_passphrase is defined
        - borg_backup_user is defined
      vars:
        borg_backup_user: googoo

- hosts: pine.ichimonji10.name
  roles:
    - user-subsonic-backup
    - role: borg-backup
      when:
        - borg_backup_passphrase is defined
        - borg_backup_user is defined
      vars:
        borg_backup_directories:
          - ~/backups
        borg_backup_user: subsonic-backup
