- name: Install Subsonic
  include_role:
    name: aur
  vars:
    aur_packages:
    - subsonic

- include_tasks: configure-subsonic.yml
- include_tasks: configure-backups.yml

- name: Start and enable Subsonic
  systemd:
    name: subsonic
    state: started
    enabled: yes
  become: true
