- block:

  # A home directory is necessary so that aurutils can cache files in
  # `~/.cache/`, and so that per-user systemd units may be created. The user
  # module creates one by default.
  - name: Create {{ aur_user }}
    user:
      name: '{{ aur_user }}'
      groups: ichi-machines
      shell: /usr/bin/bash
      home: '{{ aur_user_home }}'
      move_home: true
    notify: Lock password

  # Required by install-aurutils.sh. Possibly required by aurutils itself for
  # building packages, but this is unclear.
  - name: Give {{ aur_user }} passwordless sudo privileges
    template:
      src: aur-user
      dest: /etc/sudoers.d/{{ aur_user }}-user
      validate: 'visudo --check --file %s'
      mode: 0440

  - name: Remove references to aur-packager from /etc/sudoers
    lineinfile:
      path: /etc/sudoers
      regexp: '^aur-packager '
      state: absent
      validate: 'visudo --check --file %s'

  become: true
