- name: Install devtools (for makechrootpkg, etc.)
  pacman:
    name: devtools
  become: true

- name: Check if aurutils is installed
  command: pacman -Q aurutils
  changed_when: False
  check_mode: False
  failed_when: False
  register: result

- name: Install aurutils from the AUR
  script: install-aurutils.sh
  become_user: '{{ aur_user }}'
  when: result.rc != 0
  register: result
  become: true
