- include_tasks: create-user.yml
- include_tasks: install-aurutils.yml
- include_tasks: create-repo.yml
- include_tasks: install-units.yml
- include_tasks: package-and-install.yml
  with_items: '{{ aur_packages }}'
